---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jagger-test-data
  labels:
    username: jagger
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
