---
apiVersion: v1
kind: Service
metadata:
  name: jagger-test-service
  labels:
    username: jagger
    env: test
spec:
  type: ClusterIP
  selector:
    app: jagger-test-redis
  ports:
  - name: helloflask
    port: 6379
    targetPort: 6379
