---
apiVersion: v1
kind: Service
metadata:
  name: jagger-test-flask-service
  labels:
    username: jagger
    env: test
spec:
  type: ClusterIP
  selector:
    app: jagger-test-flask
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000
